#Comparison of exponential distributions with the Central Limit Theorem
#David C Latshaw II

##Overview  


##Simulations

```{r, echo=TRUE}
set.seed(1)
simNumber<-1000
numberSamples<-40
lambda<-0.2
simData<-matrix(rexp(simNumber*numberSamples,lambda),simNumber,numberSamples)
simMeans<-rowMeans(simData)
```  

```{r, echo=TRUE}
hist(simMeans, 
     breaks=15,
     probability=TRUE,
     main="Probability of exponential distribution with lambda=0.2",
     ylim=c(0,0.5),
     xlim=c(3,9),
     xlab="",
     ylab="Probability")
lines(density(simMeans), col="red", lty=1)
abline(v=1/lambda, col="black", lwd=3, lty=5)
xfit <- seq(min(simMeans), max(simMeans), length=1000)
ynorm<- dnorm(xfit, mean=1/lambda, sd=(1/lambda/sqrt(numberSamples)))
lines(xfit, ynorm, col="blue", lty=3)
legend('topright', c("Simulation", "Theoretical"), lty=c(1,3), col=c("red", "blue"))
``` 

```{r, echo=TRUE}
simVar<-apply(simData,1,var)
``` 

```{r, echo=TRUE}
plot(simVar, 
     main="Variance of exponential distribution with lambda=0.2")
abline(h=1/lambda^2, col="green", lwd=3, lty=5)
legend('topright', "Theoretical", lwd=3, lty=5, col="green")
``` 

```{r, echo=TRUE}
qqnorm(simMeans)
qqline(simMeans)
``` 